### ISSUE TITLE
Refused to load the script

### ISSUE THREAD

**Issue by Viktorminator** [bahmutov/code-snippets#7]
I tried to run code snippet and it gave me:
```
Refused to load the script 'https://rawgit.com/bahmutov/code-snippets/master/first-paint.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".
```

**Comment by bahmutov** [comment]
This is valid behavior. Some websites (like github.com itself) do not allow you to download and execute 3rd party scripts dynamically. This is a great security feature. In this cases you have to manually copy / paste script into the code snippet instead of trying to download it
![screen shot 2015-01-09 at 12 13 59 pm](https://cloud.githubusercontent.com/assets/2212006/5683831/2fa7a250-97f9-11e4-9d3e-2d75c9d41102.png)
